--- #YAML:1.0
name:                Geo-Google-Latitude
version:             0.08
abstract:            Google Latitude Public Location Badge Interface
license:             ~
author:              
    - Michael R. Davis (domain=>michaelrdavis,tld=>com,account=>perl)
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    GPS::Point:                    0
    JSON::XS:                      0
    LWP::UserAgent:                0
    Package::New:                  0
    Test::Simple:                  0.44
    URI:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
