Name:           perl-Geo-Google-Latitude
Version:        0.07
Release:        1%{?dist}
Summary:        Retrieves a Google Latitude Public Location Badge
License:        GPLv2
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Geo-Google-Latitude/
Source0:        http://www.cpan.org/modules/by-module/Geo/Geo-Google-Latitude-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(GPS::Point)
BuildRequires:  perl(JSON::XS)
BuildRequires:  perl(LWP::UserAgent)
BuildRequires:  perl(Package::New)
BuildRequires:  perl(Test::Simple) >= 0.44
BuildRequires:  perl(URI)
Requires:       perl(GPS::Point)
Requires:       perl(JSON::XS)
Requires:       perl(LWP::UserAgent)
Requires:       perl(Package::New)
Requires:       perl(URI)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Perl Object Interface to the Google Latitude Public Location Badge. In
order to enable Google Latitude on your mobile device, download Google Maps
Mobile and set the permission to share to the public.

%prep
%setup -q -n Geo-Google-Latitude-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE perl-Geo-Google-Latitude.spec README Todo
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Sep 06 2011 Michael R. Davis (mdavis@stopllc.com) 0.07-1
- Specfile autogenerated by cpanspec 1.78.
